name: Test cronned-rclone

on:
  push:
  pull_request:
    branches: [ master ]

env:
  DOCKER_IMAGE_TAG: adnanjaw/cronned-rclone:test

jobs:
  docker-image-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build And Export Testing Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          push: false
          tags: '${{ env.DOCKER_IMAGE_TAG }}'

      - name: Test Ofelia (without config mount)
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE_TAG }} ofelia version

      - name: Test Ofelia (with config mount)
        run: |
          # Create a dummy ofelia config file for testing
          echo "[job-exec \"example\"]\nschedule = \"@every 5m\"\ncommand = \"/bin/echo Hello Ofelia\"" > ofelia.ini
          docker run --rm -v $PWD/ofelia.ini:/config/ofelia.ini$ ${{ env.DOCKER_IMAGE_TAG }}

      - name: Test Rclone (without config mount)
        run: |
          docker run --rm ${{ env.DOCKER_IMAGE_TAG }} rclone version

        
